//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockwatch.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("stockwatch.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis algorithm.
        /// </summary>
        internal static string LBL_AnalysisAlgorithm {
            get {
                return ResourceManager.GetString("LBL_AnalysisAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze.
        /// </summary>
        internal static string LBL_Analyze {
            get {
                return ResourceManager.GetString("LBL_Analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average amplitude.
        /// </summary>
        internal static string LBL_AverageAmplitude {
            get {
                return ResourceManager.GetString("LBL_AverageAmplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex: FPT.
        /// </summary>
        internal static string LBL_ExampleOfSymbolID {
            get {
                return ResourceManager.GetString("LBL_ExampleOfSymbolID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected amplitude.
        /// </summary>
        internal static string LBL_ExpectedAmplitude {
            get {
                return ResourceManager.GetString("LBL_ExpectedAmplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected percentage.
        /// </summary>
        internal static string LBL_ExpectedPercentage {
            get {
                return ResourceManager.GetString("LBL_ExpectedPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        internal static string LBL_Favorite {
            get {
                return ResourceManager.GetString("LBL_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Favorite symbols&gt;.
        /// </summary>
        internal static string LBL_FavoriteSymbolsItem {
            get {
                return ResourceManager.GetString("LBL_FavoriteSymbolsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by.
        /// </summary>
        internal static string LBL_GroupBy {
            get {
                return ResourceManager.GetString("LBL_GroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higher.
        /// </summary>
        internal static string LBL_Higher {
            get {
                return ResourceManager.GetString("LBL_Higher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest data at.
        /// </summary>
        internal static string LBL_LatestDataAtTime {
            get {
                return ResourceManager.GetString("LBL_LatestDataAtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower.
        /// </summary>
        internal static string LBL_Lower {
            get {
                return ResourceManager.GetString("LBL_Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market/Symbols.
        /// </summary>
        internal static string LBL_MarketOrSymbols {
            get {
                return ResourceManager.GetString("LBL_MarketOrSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match count.
        /// </summary>
        internal static string LBL_MatchCount {
            get {
                return ResourceManager.GetString("LBL_MatchCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My symbol.
        /// </summary>
        internal static string LBL_MySymbol {
            get {
                return ResourceManager.GetString("LBL_MySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        internal static string LBL_Percentage {
            get {
                return ResourceManager.GetString("LBL_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage in day.
        /// </summary>
        internal static string LBL_PercentageInDay {
            get {
                return ResourceManager.GetString("LBL_PercentageInDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential symbols.
        /// </summary>
        internal static string LBL_PotentialSymbols {
            get {
                return ResourceManager.GetString("LBL_PotentialSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string LBL_Price {
            get {
                return ResourceManager.GetString("LBL_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price type.
        /// </summary>
        internal static string LBL_PriceType {
            get {
                return ResourceManager.GetString("LBL_PriceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference price.
        /// </summary>
        internal static string LBL_ReferencePrice {
            get {
                return ResourceManager.GetString("LBL_ReferencePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop watch.
        /// </summary>
        internal static string LBL_StopWatch {
            get {
                return ResourceManager.GetString("LBL_StopWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol ID.
        /// </summary>
        internal static string LBL_SymbolID {
            get {
                return ResourceManager.GetString("LBL_SymbolID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected percentage.
        /// </summary>
        internal static string LBL_UnexpectedPercentage {
            get {
                return ResourceManager.GetString("LBL_UnexpectedPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfavored.
        /// </summary>
        internal static string LBL_Unfavored {
            get {
                return ResourceManager.GetString("LBL_Unfavored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VND.
        /// </summary>
        internal static string LBL_VND {
            get {
                return ResourceManager.GetString("LBL_VND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch.
        /// </summary>
        internal static string LBL_Watch {
            get {
                return ResourceManager.GetString("LBL_Watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added &quot;{0}&quot; to favorite list.
        /// </summary>
        internal static string MSG_AddToFavoriteSuccessfully {
            get {
                return ResourceManager.GetString("MSG_AddToFavoriteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access resource to delete data.
        /// </summary>
        internal static string MSG_CannotAccessResourceToDeleteData {
            get {
                return ResourceManager.GetString("MSG_CannotAccessResourceToDeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access resource to read data.
        /// </summary>
        internal static string MSG_CannotAccessResourceToReadData {
            get {
                return ResourceManager.GetString("MSG_CannotAccessResourceToReadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access resource to write data.
        /// </summary>
        internal static string MSG_CannotAccessResourceToWriteData {
            get {
                return ResourceManager.GetString("MSG_CannotAccessResourceToWriteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a symbol.
        /// </summary>
        internal static string MSG_PleaseInputSymbol {
            get {
                return ResourceManager.GetString("MSG_PleaseInputSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a valid price other than zero.
        /// </summary>
        internal static string MSG_PleaseInputValidPrice {
            get {
                return ResourceManager.GetString("MSG_PleaseInputValidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was {0} at {1}.
        /// </summary>
        internal static string MSG_PriceDescription {
            get {
                return ResourceManager.GetString("MSG_PriceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove &quot;{0}&quot; from favorite list.
        /// </summary>
        internal static string MSG_RemoveToFavoriteSuccessfully {
            get {
                return ResourceManager.GetString("MSG_RemoveToFavoriteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started following &quot;{0}&quot;.
        /// </summary>
        internal static string MSG_StartFollowingSymbol {
            get {
                return ResourceManager.GetString("MSG_StartFollowingSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is {1} over the expectation.
        /// </summary>
        internal static string MSG_SymbolPriceIsOverExpectation {
            get {
                return ResourceManager.GetString("MSG_SymbolPriceIsOverExpectation", resourceCulture);
            }
        }
    }
}
