# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Keystore File
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" > stockwatch.keystore.asc
        gpg -d --passphrase "${{ secrets.GPG_PASSWORD }}" --batch stockwatch.keystore.asc > stockwatch.keystore
    - name: Setup appsettings.local.json File
      run: |
        echo "${{ secrets.APP_SETTINGS_FILE }}" > stockwatch/appsettings.local.json.asc
        gpg -d --passphrase "${{ secrets.GPG_PASSWORD }}" --batch stockwatch/appsettings.local.json.asc > stockwatch/appsettings.local.json
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install .NET MAUI
      run: dotnet workload install maui
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build stockwatch/stockwatch.csproj -c Release -f net8.0-android /p:AndroidSigningKeyStore=stockwatch.keystore /p:AndroidSigningKeyAlias=stockwatch /p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_KEYPASS }}" /p:AndroidSigningStorePass="${{ secrets.KEYSTORE_STOREPASS }}" --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        path: |
          ./**/*.aab
          ./**/*.apk
